### ISSUE TITLE
Getting an error when executing `npx @dhis2/cli-cluster --help`

### ISSUE THREAD

**Issue by paschalidi** [dhis2/cli#315] opened 2020-04-06 13:52 UTC
Hello y'all 👋very good work creating this package! Thanks for the good work. 

I got upon an issue while I executed `npx @dhis2/cli-cluster --help` on my mac. 

## Error description
```                  
npx: installed 190 in 9.412s
Cannot find module 'cli-table3'
Require stack:
- /Users/username/.npm/_npx/14257/lib/node_modules/@dhis2/cli-cluster/src/commands/list.js
- /Users/username/.npm/_npx/14257/lib/node_modules/@dhis2/cli-cluster/node_modules/yargs/index.js
- /Users/username/.npm/_npx/14257/lib/node_modules/@dhis2/cli-cluster/node_modules/@dhis2/cli-helpers-engine/lib/cache/middleware.js
- /Users/username/.npm/_npx/14257/lib/node_modules/@dhis2/cli-cluster/node_modules/@dhis2/cli-helpers-engine/lib/cache/index.js
- /Users/username/.npm/_npx/14257/lib/node_modules/@dhis2/cli-cluster/node_modules/@dhis2/cli-helpers-engine/index.js
- /Users/username/.npm/_npx/14257/lib/node_modules/@dhis2/cli-cluster/bin/d2-cluster
```

Is there something someone else encountered in the past?

**Comment by amcgee** [comment] 2020-04-06 14:13
Hi @paschalidi - I haven't encountered this before but will investigate.

Is there a reason you're using `npx` instead of installing the CLI globally?  We generally recommend using `yarn global add @dhis2/cli` instead of `npx` (since we use `yarn.lock` for deterministic dependency resolution).  So the following should work just fine:

```sh
> yarn global add @dhis2/cli
> d2 cluster --help
```

**Comment by amcgee** [comment] 2020-04-06 14:16
I see that the `cluster` documentation [here](https://cli.dhis2.nu/#/commands/d2-cluster) has a hiccup, it says correctly (emphasis mine):

> While you can install and run `d2-cluster` from `@dhis2/cli-cluster`, **the preferred entrypoint is the root `d2` CLI.**

But then proceeds to suggest `npx @dhis2/cli-cluster`.  This should be fixed.

**Comment by amcgee** [comment] 2020-04-06 14:24
I've [updated the docs](https://github.com/dhis2/cli/commit/de23f024e6daf5c1359d8fbb8e7a7c29fcdd28a6), will investigate the `cli-table3` issue which I can reproduce using `npx`

**Closed** 2020-04-06 14:51 UTC
